
import React, { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { User, Channel, Company } from '../types';
import { api } from '../supabaseAPI';
import { shareFile } from '../capacitorUtils';
import { Modal } from './Modal';

interface DocumentShareModalProps {
    currentUser: User;
    company:     Company;
    docType:     'DC' | 'SALES_INVOICE';
    docData:     any;
    pdfBase64:   string; // Already generated by DocumentEngine
    onClose:     () => void;
}

export const DocumentShareModal: React.FC<DocumentShareModalProps> = ({ 
    currentUser, 
    company,
    docType, 
    docData, 
    pdfBase64,
    onClose 
}) => {
    const [step, setStep] = useState<'MODE' | 'PICK_GROUP'>('MODE');
    const [sharing, setSharing] = useState(false);

    const docNumber = docData.dc_number || docData.invoice_number;
    const fileName = `${docType}_${docNumber}.pdf`;
    const docTitle = docType === 'DC' ? 'Delivery Challan' : 'Sales Invoice';

    // Queries
    const { data: channels = [], isLoading: loadingChannels } = useQuery<Channel[]>({
        queryKey: ['all_channels', currentUser.id],
        queryFn: () => api.getAllChannels(currentUser),
        enabled: step === 'PICK_GROUP'
    });

    const handleExternalShare = async () => {
        setSharing(true);
        try {
            await shareFile(fileName, pdfBase64, `Share ${docTitle}`);
            onClose();
        } catch (err: any) {
            alert(err.message);
        } finally {
            setSharing(false);
        }
    };

    const handleSendToGroup = async (channel: Channel) => {
        setSharing(true);
        try {
            // 1. Convert base64 to File
            const byteCharacters = atob(pdfBase64);
            const byteNumbers = new Array(byteCharacters.length);
            for (let i = 0; i < byteCharacters.length; i++) {
                byteNumbers[i] = byteCharacters.charCodeAt(i);
            }
            const byteArray = new Uint8Array(byteNumbers);
            const blob = new Blob([byteArray], { type: 'application/pdf' });
            const file = new File([blob], fileName, { type: 'application/pdf' });

            // 2. Upload
            const publicUrl = await api.uploadFile(file);

            // 3. Send message
            await api.sendMessage(currentUser, channel.id, `[FILE] ${publicUrl} | ${fileName}`);
            
            alert(`Sent to ${channel.name}!`);
            onClose();
        } catch (err: any) {
            alert('Failed to send to group: ' + err.message);
        } finally {
            setSharing(false);
        }
    };

    return (
        <Modal isOpen={true} onClose={onClose} title={`Send ${docTitle}`}>
            {step === 'MODE' ? (
                <div className="space-y-3 py-2">
                    <p className="text-sm text-gray-500 mb-6">How would you like to share this document?</p>
                    
                    <button 
                        onClick={handleExternalShare}
                        disabled={sharing}
                        className="w-full flex items-center gap-4 p-4 bg-white border-2 border-gray-100 rounded-2xl hover:border-blue-200 hover:bg-blue-50/30 transition-all text-left group"
                    >
                        <div className="w-12 h-12 bg-blue-50 text-blue-500 rounded-xl flex items-center justify-center text-2xl group-hover:scale-110 transition-transform">
                            📤
                        </div>
                        <div className="flex-1">
                            <span className="block text-[15px] font-black text-gray-800">Share</span>
                            <span className="block text-[11px] text-gray-400 font-bold uppercase tracking-wider">WhatsApp, Email, etc.</span>
                        </div>
                    </button>

                    <button 
                        onClick={() => setStep('PICK_GROUP')}
                        disabled={sharing}
                        className="w-full flex items-center gap-4 p-4 bg-white border-2 border-gray-100 rounded-2xl hover:border-[#008069]/20 hover:bg-[#f0f9f7] transition-all text-left group"
                    >
                        <div className="w-12 h-12 bg-[#e7f3f1] text-[#008069] rounded-xl flex items-center justify-center text-2xl group-hover:scale-110 transition-transform">
                            💬
                        </div>
                        <div className="flex-1">
                            <span className="block text-[15px] font-black text-gray-800">Send to the group</span>
                            <span className="block text-[11px] text-gray-400 font-bold uppercase tracking-wider">Share within Kramiz</span>
                        </div>
                    </button>
                    
                    <div className="pt-4 flex justify-end">
                        <button onClick={onClose} className="px-6 py-2 text-sm font-black text-gray-400 hover:text-gray-600 uppercase tracking-widest">
                            Cancel
                        </button>
                    </div>
                </div>
            ) : (
                <div className="space-y-4">
                    <div className="flex items-center justify-between mb-2">
                        <p className="text-sm text-gray-500 font-medium">Select a group to share with:</p>
                        <button onClick={() => setStep('MODE')} className="text-xs font-black text-[#008069] underline">Back</button>
                    </div>

                    <div className="max-h-[300px] overflow-y-auto space-y-2 pr-1 minimal-scrollbar">
                        {loadingChannels ? (
                            <div className="py-10 text-center text-gray-400 animate-pulse">Loading groups...</div>
                        ) : channels.length === 0 ? (
                            <div className="py-10 text-center text-gray-400 text-sm italic">No active groups found.</div>
                        ) : (
                            channels.map(ch => (
                                <button 
                                    key={ch.id}
                                    onClick={() => handleSendToGroup(ch)}
                                    disabled={sharing}
                                    className="w-full flex items-center gap-3 p-3 bg-gray-50 hover:bg-[#e7f3f1] border border-gray-100 rounded-xl transition-all text-left group"
                                >
                                    <div className="w-10 h-10 bg-white rounded-lg border border-gray-100 flex items-center justify-center font-black text-xs text-gray-700 shadow-sm group-hover:text-[#008069] group-hover:border-[#008069]/30">
                                        {ch.name[0]}
                                    </div>
                                    <div className="flex-1 min-w-0">
                                        <p className="text-sm font-bold text-gray-800 truncate">{ch.name}</p>
                                        <p className="text-[10px] text-gray-400 uppercase font-black tracking-tighter mt-0.5">{ch.type} GROUP</p>
                                    </div>
                                    <div className="opacity-0 group-hover:opacity-100 transition-opacity">
                                        <svg className="w-5 h-5 text-[#008069]" fill="currentColor" viewBox="0 0 20 20">
                                            <path d="M10.894 2.553a1 1 0 00-1.788 0l-7 14a1 1 0 001.169 1.409l5-1.429A1 1 0 009 15.571V11a1 1 0 112 0v4.571a1 1 0 00.725.962l5 1.428a1 1 0 001.17-1.408l-7-14z" />
                                        </svg>
                                    </div>
                                </button>
                            ))
                        )}
                    </div>

                    {sharing && (
                        <div className="flex items-center justify-center gap-3 py-4 text-[#008069] animate-pulse">
                            <span className="text-sm font-black uppercase tracking-widest">Sending Document...</span>
                        </div>
                    )}
                </div>
            )}
        </Modal>
    );
};
